// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mvc.Client.Data;

namespace Mvc.Client.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("Mvc.Client.Models.ActiveRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdRecipe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RealmId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RealmId");

                    b.ToTable("ActiveRecipe");
                });

            modelBuilder.Entity("Mvc.Client.Models.RealmModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectedRealmId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FarmMode")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MoneyMax")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeUpdate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Realms");
                });

            modelBuilder.Entity("Mvc.Client.Models.ActiveRecipe", b =>
                {
                    b.HasOne("Mvc.Client.Models.RealmModel", "Company")
                        .WithMany("ActiveRecipes")
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
